import js from "@eslint/js";
import tseslint from "typescript-eslint";
import globals from "globals";

export default tseslint.config(
  {
    ignores: [
      ".output/**",
      ".wxt/**",
      "node_modules/**",
      "coverage/**", // generated by vitest --coverage
      "src/data/generated/**", // generated CMUdict bundle, not hand-written
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,

  {
    languageOptions: {
      parserOptions: {
        projectService: {
          // Config files are plain JS and are not part of any tsconfig project,
          // so they use the default project. `**` globs are rejected by
          // typescript-eslint for performance reasons, hence explicit filenames.
          allowDefaultProject: ["*.js", "*.mjs", "eslint.config.js", "scripts/*.mjs"],
        },
        tsconfigRootDir: import.meta.dirname,
      },
      globals: { ...globals.browser, ...globals.webextensions },
    },
    rules: {
      // --- Correctness -----------------------------------------------------
      "no-console": ["warn", { allow: ["warn", "error", "info"] }],
      eqeqeq: ["error", "always"],
      "no-implicit-coercion": "error",
      "prefer-const": "error",
      "no-var": "error",

      // --- Spec section 9: security ----------------------------------------
      // No eval / no Function constructor / no remote code.
      "no-eval": "error",
      "no-implied-eval": "error",
      "no-new-func": "error",
      "no-script-url": "error",

      // --- Hygiene ---------------------------------------------------------
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "@typescript-eslint/consistent-type-imports": [
        "error",
        { prefer: "type-imports", fixStyle: "separate-type-imports" },
      ],
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/explicit-module-boundary-types": "error",
      "@typescript-eslint/switch-exhaustiveness-check": "error",
      "@typescript-eslint/no-floating-promises": "error",
      "@typescript-eslint/no-misused-promises": "error",

      // --- DOM hygiene: spec section 4.1/4.2 use shadow DOM, never innerHTML
      "no-restricted-properties": [
        "error",
        {
          object: "element",
          property: "innerHTML",
          message:
            "Never assign innerHTML: selection text and dictionary responses are untrusted. Use textContent or a DOM builder.",
        },
        {
          object: "element",
          property: "outerHTML",
          message: "Never assign outerHTML. Use replaceWith()/remove().",
        },
      ],
    },
  },

  // Test files: allow non-null assertions on querySelector helpers, and allow
  // `async` stubs that stand in for promise-returning APIs without awaiting.
  {
    files: ["tests/**/*.ts"],
    rules: {
      "@typescript-eslint/no-non-null-assertion": "off",
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/require-await": "off",
    },
  },

  // -------------------------------------------------------------------------
  // Overrides that must come last, since flat config applies later blocks on top.
  // -------------------------------------------------------------------------

  // Node build scripts: not browser code, and not type-checked by tsc, so the
  // type-aware rules do not apply. `console.log` is how a CLI reports its
  // output, which is the whole point of these files.
  {
    files: ["scripts/**/*.mjs"],
    extends: [tseslint.configs.disableTypeChecked],
    languageOptions: { globals: { ...globals.node } },
    rules: { "no-console": "off" },
  },

  // The lint config itself. It uses `import.meta.dirname` and reads its own
  // package.json, none of which the browser-oriented type config knows about.
  {
    files: ["eslint.config.js"],
    extends: [tseslint.configs.disableTypeChecked],
    languageOptions: { globals: { ...globals.node } },
  },
);